### ISSUE TITLE
Someday: Return generator that makes Event Documents from mongo Cursor

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/metadatastore#102]
When there are huge numbers of Events:

```
(Document(e) for e in Cursor)
```

**Comment by tacaswell** [comment]
How did I close this?

**Comment by danielballan** [comment]
No idea.

**Comment by ghost** [comment]
@tacaswell had no @tacaswell to oversee his actions. Open loop lol

**Comment by danielballan** [comment]
When @tacaswell errs, Zeus himself strikes down the offending commit. :zap:

**Comment by ghost** [comment]
This conversation is why people tell this sort of stuff about us: http://rs2img.memecdn.com/engineers-personality_o_198312.webp
