### ISSUE TITLE
Allow searching on parent Document's uid.

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/metadatastore#114]
e.g., `find_event_descriptors(run_start_uid=...)`

Is this something that can be done, @arkilic? As discussed on the train, I agreewe should prefer our uids over mongo's ids wherever possible, but the commands don't currently support that.

**Comment by ghost** [comment]
Yes, we can do this. I will get to this asap! We could make uid primary_key in order to eliminate the confusion between _id and uid. Any thoughts?

**Comment by danielballan** [comment]
I think that is not the idea, actually. @tacaswell?

**Comment by tacaswell** [comment]
That _also_ sounds like a breaking change to the schema that would require database migration.

I am ambivalent on the change and :-1: on db migration.

**Comment by ghost** [comment]
In any database model, you can assign primary and foreign keys to documents/tables, so there is no issue in that respect. 
:-1:  on migration on my side too. We deployed this to way too many beamlines to change this around. It was me hoping to normalize the db as much as we can but it is an expensive change that is not worth the effort.

**Comment by ericdill** [comment]
Closed by #167
