### ISSUE TITLE
add ability to pass in a filename to `load_configuration`

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/metadatastore#124]
Be able to explicitly pass in a file to be ultimate authority on configuration values.

**Comment by ghost** [comment]
How do you think we should do this?

**Comment by ericdill** [comment]
What sort of format were you considering for this file?

**Comment by tacaswell** [comment]
I was going to go with the same format we have now, just allow it to be consumed directly, (rather than being found in one of the 'standard' places).

**Comment by danielballan** [comment]
Our plan for databroker configuration addresses this use case.
