### ISSUE TITLE
find_**() fails with too many database entries

### ISSUE THREAD

**Issue by ghost** [NSLS-II/metadatastore#129]
If no args are provided to find routines and there are too many documents(not sure exactly how many since we populated the db to some 600 million events and 110K headers before I did this test), daemon raises an exception: Too many arguments to sort.

**Comment by tacaswell** [comment]
can you reproduce this in the mongo shell?

**Comment by ghost** [comment]
I can but the machine does not respond at this very moment. Need to figure out what's going on with the xf23id1-ioc2 first.

**Comment by ericdill** [comment]
csx is down all morning for networking upgrades

**Comment by ericdill** [comment]
@arkilic has this issue been resolved?

**Comment by ericdill** [comment]
or @tacaswell

**Comment by tacaswell** [comment]
This is resolved as everything now indexes on time.
