### ISSUE TITLE
Add bulk event insertion

### ISSUE THREAD

**Issue by klauer** [NSLS-II/metadatastore#162]
Large fly scans (10k+ points) at the HXN acquire with minimal overhead; inserting all of the events into metadatastore can often take longer than the scans themselves.

I'd like to see an option to add all of the events at once into the database - bulk insertion - which hopefully should cut down on the overhead.

Bulk datum insertion in filestore (and ophyd's `AreaDetectorFileStore`) will also be necessary, I believe. Should I open an issue there as well or will this suffice?

**Comment by tacaswell** [comment]
This is good enough.  Dan also made an issue in the wishlist tracker.

**Comment by ericdill** [comment]
You could also just insert one event for each fly scan, couldn't you?

**Comment by tacaswell** [comment]
But that makes it more annoying to work with on the analysis side as your 'events' would be either rows or whole scans. My understaning from @licode is that you want to be able to work on individual spectrum.

**Comment by ghost** [comment]
It is prettier to get one event from the db vs multiple events, especially in terms of performance. It might be annoying to unpack stuff on the analysis side but I think we should look into what @ericdill suggested.

**Comment by klauer** [comment]
@ericdill It's certainly a possibility - but then we wouldn't be consistent with the storage of step- and fly-scan data. I think that's an important thing, personally.

I think even in that case filestore would still have to be changed...

**Comment by tacaswell** [comment]
I think changing the meaning of 'event' in this case is a very good backup plan, but the first attempt should be to make the current system faster.

**Comment by ericdill** [comment]
I was under the impression that "event" was designed to mean whatever makes the most sense given the experiment that is being run. As such, this does not feel like "changing the meaning of event", but instead using the framework we designed

**Comment by tacaswell** [comment]
meaning change the meaning of event from what is currently implemented as the meaning of event is this case.

**Comment by klauer** [comment]
I think I see what you mean. Perhaps below is too much detail for this specific issue report, but I'd like to pick your brain about the following at some point, should we try to go down this path:

So say we have an `Event` that's now a full fly-scan. What do the filestore datum look like? Would a single datum hold the full image sequence for the scan? Is there any way around keeping two separate implementations of the ophyd filestore savers for the different scan types? And how would you recommend keeping a consistent interface for the user grabbing both types of scans from the broker?

**Comment by stuwilkins** [comment]
All,

Do you think we should get together for 30 mins to thrash this out. If my memory serves me correctly and “event” as a concept as a bundle which made sense to be collected together. Therefore I could see a flyscan as a single event as long as each value is a value timestamp tuple. Make sense?

S

On Aug 11, 2015, at 9:36 AM, K Lauer <notifications@github.com<mailto:notifications@github.com>> wrote:

I think I see what you mean. Perhaps below is too much detail for this specific issue report, but I'd like to pick your brain about the following at some point, should we try to go down this path:

So say we have an Event that's now a full fly-scan. What do the filestore datum look like? Would a single datum hold the full image sequence for the scan? Is there any way around keeping two separate implementations of the ophyd filestore savers for the different scan types? And how would you recommend keeping a consistent interface for the user grabbing both types of scans from the broker?

**Comment by ericdill** [comment]
After an offline conversation with @klauer it seems that there are two issues here. One is generating all of the filestore `Datum`'s & `Resource`'s that then needs to be correlated with the metadatastore `Event` info. The other is generating all of the metadatastore `Event`'s. For now, @klauer would be satisfied with a bulk event insertion API into metadatastore, but we still need to sort out how to best generate all of the filestore datum/resource insertion.

**Comment by ericdill** [comment]
Again, :+1: to @tacaswell 's PR #167
