### ISSUE TITLE
build pymongo for python 3.5

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/metadatastore#177]
If we build pymongo for python 3.5 then we can test python 3.5 on travis

**Comment by tacaswell** [comment]
pymongo is pure-python and can be pip installed.

**Comment by ericdill** [comment]
pymongo has at least one c file in its repo

**Comment by ericdill** [comment]
https://github.com/mongodb/mongo-python-driver/blob/master/setup.py#L238

**Comment by danielballan** [comment]
We are testing on 3.5 now. I can't tell from the .travis file which channel this is coming from, but it was resolved one way or another.
