### ISSUE TITLE
add capped collections

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/metadatastore#182]
As discussed with @arkilic capped collections provide an easy way to essentially monitor a collection via a tailable cursor.  The capped collections should be added to by all of the insert operations.
- [ ] add code to make sure that parallel capped collections exist for start, stop, descriptor
- [ ] add code to insert into the parallel capped collection 
- [ ] write example monitor scripts

**Comment by ghost** [comment]
We should have a short discussion about the size of capped collections, what the api for monitor routines looks like, and possibility to replace the existing caching layer with capped collection(since higher throughput).
