### ISSUE TITLE
Shadowing the 'commands' python 2 built in module

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/metadatastore#191]
Not sure if we care, but apparently `commands` is a built in module that you can import in python 2.  It was removed in python 3. Should probably rename commands to something else if we care about py2

**Comment by klauer** [comment]
Why is this an issue when relative imports are used internally?

**Comment by ghost** [comment]
Also, I don't think anybody is using mds in py2 in or outside nsls2.

**Comment by ericdill** [comment]
Very well. Thanks gents
