### ISSUE TITLE
ObjectID in the run_header

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/metadatastore#20]
VisTrails is whining about not knowing what an ObjectID is. Can you remove that from the run_header or will that blow a whole bunch of stuff up?

**Comment by ghost** [comment]
I assume now that you wanted me to provide the search functionality on this very component we will keep this. Please resubmit if you'd like to oppose

**Comment by ericdill** [comment]
Yes, this is fine. The problem was with me getting back `ObjectID(some_hashed_id)` because I kept getting errors on my environment not knowing what an `ObjectID` is
