### ISSUE TITLE
Notes about migration

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/metadatastore#200]
@arkilic's current approach add a `configs` key (de-normalizing the old "beamline configs" collection) and a `migrated` key, set to `True`. We should discuss if we are happy with those choices before we roll this out. Note that @tacaswell's MDS refactor introduces "version 0" for the present deployment and "version 1" for the service deployment, the main difference being uid as primary key and making configs embedded docs rather than stand-alone collection. Maybe we should favor version in place of "migrated"?

Also noting here that the refactored MDS can read both and finds them equal.

**Comment by tacaswell** [comment]
That version number does not show up anywhere in the database, it is purely a software side thing.

**Comment by danielballan** [comment]
Understood. My question for the group is, should a version key be added as part of the migration? I would say that that is better than migrated=True, which obviously won't help the _next_ time we migrate. But maybe neither is needed.

**Comment by ghost** [comment]
migrated=True is a placeholder thing I added to the migration script in order to delete all migrated documents in case something goes wrong. We could alternatively use time or version. Let's get together early next week

**Comment by danielballan** [comment]
@arkilic That level of caution is appreciated. There are a couple other ways we could go here, as I think about it. Yeah, let's discuss in person.
