### ISSUE TITLE
ENH: corrections to MDS

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/metadatastore#237]
I know there was some work done in the past on allowing corrections to the MDS documents. Would it be possible to bring that back?
I think @ericdill might have been the last person to touch that feature.

**Comment by klauer** [comment]
I have no real opinion on this - but can you fill us in as to why you need this feature?

**Comment by CJ-Wright** [comment]
I recently took some data and need to correct the uuid in the foreground data which links it to the calibration data.

**Comment by ghost** [comment]
What do you mean by "correcting" the uid?

**Comment by CJ-Wright** [comment]
Because of the setup at XPD I specified two uuids (which are seperate from the run, event, image, or any other uuid which is created by the database stack) these two uuids link the foreground data to the background data (they share the same uuid, and the background data has a flag to note that it is background) and the foreground data to the calibration data (again they share this uuid and have a flag). However, for some of the runs I used the wrong uuid for the calibration data. I would like to correct this. More broadly I imagine that users may have the (hopefully rare) problem of entering erroneous metadata which would need to be fixed.

**Comment by CJ-Wright** [comment]
See #150 and [NSLS-II/wishlist#1](https://github.com/NSLS-II/wishlist/issues/1)

**Comment by tacaswell** [comment]
This should follow the pattern of https://github.com/NSLS-II/filestore/pull/58 and add a MDS_DANGER sub-class which allows for updating (and logging there of) user specifying fields along with the needed updates to broker.

**Comment by danielballan** [comment]
Track https://github.com/NSLS-II/databroker/issues/180
