### ISSUE TITLE
ENH: include database uid in header

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/metadatastore#260]
I might be extremely useful to include some sort of database identifying uid in each header, that way we could access the database that the header came from only knowing the header. An example of this is getting all the events from an unknown databroker given the `run_start` header.
Previously discussed with @danielballan and @tacaswell

**Comment by tacaswell** [comment]
This can not go in any of the documents (as at document creation time the `RunEngine` does not know where the document will be written too (or if it will be written to more than one)).

'header' is a notion from databroker, not from mds.  This sort of thing should be tacked on on the way out by the databroker, not part of the 'core' document schema.
