### ISSUE TITLE
What is the best way to get an event given an event uid?

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/metadatastore#261]
What is the best way to get an event given an event uid?
Methods exist to do the same for starts, stops, and descriptors but not events.

**Comment by ghost** [comment]
https://github.com/NSLS-II/metadatastore/blob/a72733f1e942cb04578a07855d1b092ec066437c/metadatastore/examples/sample_data/multisource_event.py#L63

In the API: https://github.com/NSLS-II/metadatastore/blob/65cc5775c5d0bf71b88f3b28907c248e722a703e/metadatastore/mds.py#L491

**Comment by CJ-Wright** [comment]
Thank you!

**Comment by tacaswell** [comment]
Why do you want to get an event by event uid?

**Comment by ghost** [comment]
@tacaswell you beat me to it

**Comment by CJ-Wright** [comment]
Because when I insert a new event and want to pass the information held in that new event I only get an event_uid back

**Comment by CJ-Wright** [comment]
It will be helpful for chaining callbacks together.

**Comment by tacaswell** [comment]
You also _have_ the event if you just inserted it.

**Comment by CJ-Wright** [comment]
Is it the exact same formatting and such?
My understanding was that `insert_event` just gave back the uid. I have the dict but the dict doesn't have all the info in it (eg the `filled` key)

**Comment by tacaswell** [comment]
`filled` is optional, you pass everything else in and you get back the uid.  If you are constructing the events (and have the descriptor) you should also know which keys are filled or not.
