### ISSUE TITLE
Filled status not supported

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/metadatastore#262]
[Filled](https://github.com/NSLS-II/event-model/blob/master/event_model/schemas/event.json#L11) is a potential field for events in the schema. However, it is not a kwarg in `mds.insert_event` leading to `unexpected kwarg` errors.

**Comment by tacaswell** [comment]
filled should not go into the database.

**Comment by CJ-Wright** [comment]
Thank you!
