### ISSUE TITLE
ENH: stash number of events in run_stop

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/metadatastore#263]
Would it be possible to stash the number of events (potentially on a per descriptor basis) in the `run_stop` document? This could be very convenient a) for just seeing how many events you have, b) be very helpful for broadcasting streams together.

**Comment by tacaswell** [comment]
We have discussed this before and ended up against making it required, but the schema is flexible so go right ahead!  Would definitely have to be per-descriptor.

The main reason against this is that it would require a fair amount of coordination at data collection time (which we currently _have_) but want to leave open the possibility of data collection that by-passes the run engine for document generation, particularly for the fly-scan applications.  We made this decision fairly early, might be worth revisiting for data collection.

Let us know how it goes!

**Comment by ghost** [comment]
It would definitely be nice to know how many events/stream for tweaking streaming performance etc. I am very eager to see how this will go.

**Comment by CJ-Wright** [comment]
I can do this for the analysis workflow and see how it goes.

**Comment by danielballan** [comment]
Still interested to hear how this goes, @CJ-Wright. Closing the issue -- follow up on databroker if you ever do give this a try.
