### ISSUE TITLE
Setup.py fails to find README.md

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/metadatastore#3]
setup.py looks for README.md, can't find it and fails.

`python setup.py install
0.0.2
Traceback (most recent call last):
  File "setup.py", line 80, in <module>
    long_description=read('README.md'),
  File "setup.py", line 34, in read
    return open(os.path.join(os.path.dirname(__file__), fname)).read()
IOError: [Errno 2] No such file or directory: 'README.md'`

**Comment by ghost** [comment]
Try to pull it now and retry.

On Jul 23, 2014, at 11:12 AM, Christopher J. Wright <notifications@github.com<mailto:notifications@github.com>> wrote:

setup.py looks for README.md, can't find it and fails.

python setup.py install
0.0.2
Traceback (most recent call last):
File "setup.py", line 80, in <module>
long_description=read('README.md'),
File "setup.py", line 34, in read
return open(os.path.join(os.path.dirname(**file**), fname)).read()
IOError: [Errno 2] No such file or directory: 'README.md'
