### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/metadatastore#46]
Generated documentation (i.e., Sphinx) should be on a `gh-pages` branch and not under version control

**Comment by ghost** [comment]
Why can’t it be in both places?

On Dec 1, 2014, at 11:38 AM, Eric Dill <notifications@github.com<mailto:notifications@github.com>> wrote:

Generated documentation (i.e., Sphinx) should be on a gh-pages branch and not under version control

**Comment by ghost** [comment]
All I am saying is, in every controls group python project we roll out, the documentation is part of version control. Those two are examples from physics midlayer services
