### ISSUE TITLE
Add a search function that simply returns a list of events.

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/metadatastore#59]
As per our discussion today, @arkilic.

**Comment by ghost** [comment]
What should the search criteria be? Currently, it is a header object. I could get last, say 50 header, and return only events. find_events(limit) will go fetch the last 'limit' headers and return you only events associated with those headers.
For each event object returned, you can always do event_object.header to get the corresponding header

**Comment by danielballan** [comment]
How about this:

```
search_time_range(beamline_id, start_time, end_time)
search_recent_runs(limit=50)
search_scan(beamline_id, scan_id)
```

There could (and should) be many other search criteria, leading to many optional kwargs and possible other top-level functions, but I'd like to start small.

**Comment by danielballan** [comment]
P.S. Some constraint on time is essential because, in our current thinking at least, the DataBroker will return popular ChannelArchiver data by default, and it needs to know which time range to request. It can take that time range from `start_time`, `end_time`, or it can infer it from the times of the Events.

**Comment by ghost** [comment]
Per our discussion with Tom, I don’t think we need to have a beamline_id field. If you are so far into your analysis that you need to pull events, you better know what beamline you’re working on. Also, we store this information in the headers not events. If this is an event specific search, we should only hit the event collection. If you guys have a use case and this is a must-have item, I can easily add it to MDS. 

I agree. I believe scan_id would be quite essential. This means we need to hit header collection and return both headers and events in the future. 

Having a time constraint makes excellent sense.
Implementation detail: I want to call this range_start, range_end since people might confuse this with header start and end times even though they're now deprecated. Do you want to use unix time or datetime? I can do both in MDS. I prefer unix time because of accuracy.

**Comment by danielballan** [comment]
Per Eric, who is sitting here, "We need to be able to handle branches like XPD1 and XPD2, so let's keep the `beamline_id` field." I'll add that we can always hide that from the user if we want to, whether at the Broker or Muggler layer, so that they aren't typing that over and over.

OK, give me a UNIX time.

Eric and I prefer `start_time` and `end_time`. It's too early to worry about deprecations.

**Comment by ghost** [comment]
Then, I will add the beamline_id field to the events as well.

It is an inner facing api for broker so I guess it doesn’t matter. I think we should start thinking about deprecation. We already commissioned beamlines and have data sitting with fields called start_time, end_time…

**Comment by licode** [comment]
Do you think it is reasonable to split the search function into two functions: search_mds and search_ca? And we will have a top search controller to call them. So later we can update anyone of them without touching others.

**Comment by ghost** [comment]
Those two search routines exist independently via mds and ca libraries. We can either use those directly and/or add them to dataBroker api. The point of dataBroker is to glue all these different tools together. 

What do you mean by top search controller?

**Comment by licode** [comment]
Right now we have a search function in databroker api. I am talking about adding another layer in databroker to control the search functions, such as we can search either from mds, ca or both, or something else. This is purely for the purpose of code's maintenance and expansion. Things might become a bit complicated when we connect the searching results to data muggler.

**Comment by danielballan** [comment]
@licode In the end, the broker will never let users pick apart individual sources. Its whole role is to hide the separate sources from the user. But if you need calls like this for development purposes, perhaps we can introduce them as private, undocumented functions and remove them later. Open an issue on databroker.

**Comment by danielballan** [comment]
@ericdill @tacaswell @arkilic I am going to update `simple_broker` to use two new MDS api functions: `find_header` and `find_event`. I will also update dummy MDS to reflect this I don't need an additional function to get what I want, so I will close this issue.

@ericdill, Arman put more though into what we're calling "data exploration" that I did, and he has implemented a very nice collection of functions. I think `find`, which returns `(dict_of_headers, dict_of_events)` is the most useful for data exploration. One can explore "up" in the hierarchy starting with an `Event` or "down" in the hierarchy starting with a `Header`. It's flexible, but not unwieldy. This is what the muggler/replay/VT should we using for data exploration going forward.
