### ISSUE TITLE
Brainstorm from Dan & Arman during MDS refactor

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/metadatastore#69]
Random thoughts occurred to us while refactoring MDS to meet the jsonspec.
- Should `BeamlineConfig` be an `EmbeddedDocument`? Lookup would be faster (fewer queries) at a small but significant storage cost. This scales with runs, not events or descriptors, the cost would be moderate.
- Neither of us like the names `BeginRunEvent` and `EndRunEvent` and might prefer `RunHead` and `RunTail`.

**Comment by tacaswell** [comment]
If this is going to happen I think it _must_ happen before we deploy to XPD.

**Comment by stuwilkins** [comment]
Ok, comments like that scare me. Can I suggest that we all get together Tuesday AM, or even remotely to go over the XPD deployment and what _has_ to happen for it. Do you want me to call that?

S

On Feb 14, 2015, at 11:47 PM, Thomas A Caswell <notifications@github.com<mailto:notifications@github.com>> wrote:

If this is going to happen I think it must happen before we deploy to XPD.

**Comment by ericdill** [comment]
Comments like @danielballan or comments like @tacaswell ?

Getting together remotely is a much better idea, as it gives us >2 hours to implement whatever it is we decide.  I think you scheduling it would be good. I'm free all day today and all day tomorrow

**Comment by tacaswell** [comment]
I am also free all day both days

**Comment by ericdill** [comment]
Renames done by https://github.com/NSLS-II/metadatastore/commit/8ea3581fc26096d241bc4f17b4b9501a9e40faf5
