### ISSUE TITLE
remove time_as_datetime from Event

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/metadatastore#78]
We do not want to support this long term and removing it later will require data migration. This needs to be done as soon as possible before we have lots of data to migrate.

**Comment by ericdill** [comment]
I'm not sure that this sentiment is held by everyone in this project.  Having this field is so freaking valuable whenever you need to look at the database in the mongo shell. Do you agree @arkilic ?

**Comment by tacaswell** [comment]
Yes, wrote this sitting in a room with @dchabot @danielballan @arkilic and there was consensus.

@stuwilkins Does not want this supported long term or to be publicly visible.  Because we decided to lock-down the Event Document (as a `Document` not an `DynamicDocument`) if we in the future remove this from the Event document will require data migration which will be a major pain.  Doing this now will save us a good deal of pain later.

Everything _but_ Event still has this field (but it is not in the schema, commands.py just throws it in).

**Comment by ericdill** [comment]
@arkilic agrees with you @tacaswell . I'll rescind my complaint
