### ISSUE TITLE
add alias to all odm templates

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/metadatastore#94]
This is so that we can control the server of mds, fs, and analysis store separately if we want to.

**Comment by ericdill** [comment]
This incurs horrible state management problems, right?

**Comment by ghost** [comment]
If I understood this right, it has the potential of breaking various things. What do you mean by controlling the server @tacaswell ?

**Comment by tacaswell** [comment]
This should not break anything and there is _already_ horrible state management in mongoengine.

The issue is that the way that mongoengine deals with server connections is that it gives each server/db combination an 'alias' internally, with a default if you don't specify it.  This means that if you have a MDS db on one server and a FS db on a different server (or just in a different mongo database on the same server) mongoengine will bind _both_ to the same server/db pair.  By giving the odm templates an alias to bind to, and then adding that same alias in the connection decorator we can make sure we don't start to mix things we don't want to mix.

**Comment by ghost** [comment]
The neat way is to make this a service, not this. If we separated the server/client, mongengine would stay on the server side(which is its original intended place). We would only have to specify in our mds or fs client library the server to be connected to. This way, we get around the mongoengine connection management issue. 
We are aliasing too many things in various places. I am a fan of aliasing but we should avoid over-using them. At the end of the day, we have to manage these aliasing behavior which is my primary concern.

**Comment by tacaswell** [comment]
Yes, but PR #97 does this and works _now_.

**Comment by ghost** [comment]
Because it works doesn't mean it's right and/or neat (quoting you Tom :D)

**Comment by tacaswell** [comment]
Done in #97
